### ISSUE TITLE
Feature request: add support for arrow functions in filters

### ISSUE THREAD

**Issue by rellafella** [zackad/prettier-plugin-twig#19]
Twig has some included filters that can take an arrow function
https://twig.symfony.com/doc/3.x/filters/map.html

Not sure if it would be best to build this out as a plugin or built into the core but the arrow completely breaks the parser.

**Comment by zackad** [comment]
This is also pain point I face when using this plugin. It force me to create custom twig filter to circumvent this limitation. Definitely will be added.

**Comment by fvwanja** [comment]
This would be soooo super awesome to have!

**Comment by marcwieland95** [comment]
Same issue to me. I was formatting a full code base and the only place I needed to refactor something which made the code worse was with the `map` filter. It would be very handy to have support for that as well and not do foreach loops instead.

**Comment by jannisborgers** [comment]
Thought I could give it a try and added PR #42 to hopefully resolve this issue.

Here are my notes. For anyone interested, and to maybe document how to add new features in the future.

### Step 1: Let lexer tokenize arrow functions
* Add new token type:

https://github.com/zackad/prettier-plugin-twig/blob/c38344121732798ea32c4388989514bb8acdfb1d/src/melody/melody-parser/TokenTypes.js#L47

* Identify and tokenize arrow function correctly instead of making it an assignment (`=`) and an operator (`>`) (this is the error we all see right now):

https://github.com/zackad/prettier-plugin-twig/blob/c38344121732798ea32c4388989514bb8acdfb1d/src/melody/melody-parser/Lexer.js#L47
https://github.com/zackad/prettier-plugin-twig/blob/c38344121732798ea32c4388989514bb8acdfb1d/src/melody/melody-parser/Lexer.js#L349-L357

### Step 2: Let parser identify arrow function in addition to other filter arguments
`matchFilterExpression()` and `matchArguments()` are called to collect the arguments of the filter that is applied to a variable
* Already supported scenarios:
  * no arguments: `someString|raw`)
  * some arguments, comma-separated: `someArray|batch(3, 'No item')`
  * named arguments via assignments: `someDate|data_uri(mime="text/html", parameters={charset: "ascii"})`
* Newly supported scenarios:
  * arrow function with one argument: `someArray|filter(item => item.amount > 4)`
  * arrow function with multiple arguments: `someArray|map((value, key) => item.firstName ~ " " ~ item.lastName)`
  * arrow function, plus other filter arguments, e.g. `numbers|reduce((carry, v, k) => carry + v * k, 10)`, where `10` is the second filter argument and the arrow function is the callback. This works because comma-checks are in place for multiple filter arguments already and `matchArguments()` is called recursively for each filter argument.

https://github.com/zackad/prettier-plugin-twig/blob/c38344121732798ea32c4388989514bb8acdfb1d/src/melody/melody-parser/Parser.js#L923-L961

### Step 3: Add node type:
Used to identify the arrow function as a whole

https://github.com/zackad/prettier-plugin-twig/blob/c38344121732798ea32c4388989514bb8acdfb1d/src/melody/melody-types/index.js#L326-L339

### Step 4: Parse arrow function itself
**Arguments** is everything between filter opening parenthesis `(` and arrow `=>`
* Possible scenarios:
* option 1: single argument, e.g. `item =>`
* option 2: multiple arguments inside their own parenthesis, e.g.`(value, key) =>`
**Body** everything from arrow `=>` until the closing filter parenthesis `)`
* How do we parse this?
* Can be a string, can be a comparison, calculation, can be concatenated strings…
* What about commas that would end the filter argument?

https://github.com/zackad/prettier-plugin-twig/blob/c38344121732798ea32c4388989514bb8acdfb1d/src/melody/melody-parser/Parser.js#L963-L1004

### Step 5: Add `ArrowFunction` printer
After the arrow function as a whole is added as a node, it has props for params and body, which can be used inside the printer for formatting.

This is where proper formatting can be achieved by defining the output of the printer. 

I’m working on another PR which allows more fine-grained control over line-breaks for filters (and objects), because I think needless indentation of single arguments or properties, or multiple short ones, is not helping code legibility.

https://github.com/zackad/prettier-plugin-twig/blob/c38344121732798ea32c4388989514bb8acdfb1d/src/print/ArrowFunction.js#L1-L28

## Additional scenarios:
I have only tested arrow functions in tags `{% %}` as opposed to expressions `{{ }}` briefly, but they seem to work as well now (?)

## Scope
As far as I know, arrow functions are only available in map, filter and reduce filters in Twig 3. While there is a [Craft plugin to make it work everywhere else](https://github.com/nystudio107/craft-closure), and that plugin got [a lot of thumbs up for being native Twig 4 functionality](https://github.com/twigphp/Twig/issues/3951#issuecomment-1922578351), I think making it work with the three above will improve this plugin a lot.

**Comment by marcwieland95** [comment]
Thanks @jannisborgers and @zackad. Amazing work 🙏
